#!/usr/bin/env python

from __future__ import print_function
import sys
from subprocess import check_output

protected_branch = "master"

# Compatibility for Python2/3 input methods:
if sys.version_info >= (3, 0):
    input_fcn = input
else:
    input_fcn = raw_input

if __name__ == "__main__":
    branch_name = (
        check_output(["git", "symbolic-ref", "--short", "HEAD"])
        .strip()
        .decode(encoding="UTF-8")
    )
    if branch_name == protected_branch:
        try:
            # Needed for user input in git-hooks
            sys.stdin = open("/dev/tty")
            re_edit = input_fcn(
                "You're about to commit to master, is that what you intended? [y/n] "
            )
            while re_edit not in ("y", "yes", "n", "no"):
                re_edit = input_fcn(
                    "Invalid choice '%s'.  Yes, commit or no, abort?. [y/n] "
                    % (re_edit,)
                )
            if re_edit.lower() in ("y", "yes"):
                sys.exit(0)
            else:
                sys.exit(1)
        except KeyboardInterrupt:
            print("Abort by keyboard interrupt")
            sys.exit(1)
