#!/usr/bin/env python3

import sys
from subprocess import check_output

import hook_utils

PROTECTED_BRANCH = "master"

if __name__ == "__main__":
    branch_name = (
        check_output(["git", "symbolic-ref", "--short", "HEAD"])
        .strip()
        .decode(encoding="UTF-8")
    )
    if branch_name == PROTECTED_BRANCH:
        try:
            # Needed for user input in git-hooks
            hook_utils.open_console_input()
            msg = "You're about to commit to master, is that what you intended? "
            options = ["Yes", "no", "abort"]
            user_choice = hook_utils.ask_user_choice(msg, options)
            if user_choice == "Yes":
                sys.exit(0)
            else:
                sys.exit(1)
        except KeyboardInterrupt:
            print("Abort by keyboard interrupt")
            sys.exit(1)
